name: Snake Animation

on:
  schedule:
    # run automatically every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository   
        uses: actions/checkout@v4
      
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: biaProjects
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github&color_snake=blue
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=blue

      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
